### ISSUE TITLE
make router prefer ipv6

### ISSUE THREAD

**Issue by pywy18** [alexhaydock/openbsd-ipv6-focused-home-router#2]
nice blog post.
what came to my mind when reading you is to favor ipv6 in front of ipv4 by tunning /etc/resolv.conf :
` family inet6 inet4`

Cheers

**Comment by alexhaydock** [comment]
Thanks!

Sounds like a sensible addition, but shouldn't this be covered by OpenBSD correctly implementing [RFC 6724](https://www.rfc-editor.org/rfc/rfc6724) which suggests it ought to prefer IPv6 over IPv4 in most situations anyway?

Or is there a specific scenario you have in mind here?

**Comment by pywy18** [comment]
if I understand well the man page,  by default ipv4 is queried first, but I have no explanation regarding RFC's guidances. 
On my side I set the family setting above on all my openBSD hosts to favor ipv6...
I keep track on ipv6 vs ipv4 traffic for my whole lan since quite some years,  Just a way for me to know what part of my internet traffic is ipv6 before I try to switch full ipv6 like you :) (clearly not the moment yet)

**Comment by alexhaydock** [comment]
Looking at `resolv.conf(5)` it seems you're right, so I've added this now. Also took the time to add some comments to the rest of the file.

I guess the scope of this is fairly narrow since it will only impact traffic originating _from_ this host as a router, whereas 99.9% of what we deal with will probably be passing _through_ the router, but it's worth adding. Thanks! 😄
